--1
create database [Customer_DB] ON PRIMARY
(Name ='Customer_DBX',FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\Customer_DB.mdf')
LOG ON
(Name ='Customer_DB_log',FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\Customer_DB_log.ldf')
COLLATE SQL_Latin1_General_CP1_CI_AS
--2
ALTER DATABASE Customer_DB MODIFY NAME = CUST_DB

--3
use CUST_DB
EXEC sp_changedbowner 'sa'

--4
USECUST_DB;
ALTER DATABASE CUST_DB SET AUTO_SHRINK ON
--5
CREATE DATABASE [SalesDB] ON PRIMARY
(Name = 'SalesDB', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\SalesDB.mdf',SIZE=3072KB,MAXSIZE=UNLIMITED,FILEGROWTH=1024KB),
FILEGROUP (MyFileGroup)
(Name = 'SalesDB_FG', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\SalesDB_FG.ndf',SIZE=3072KB,MAXSIZE=UNLIMITED,FILEGROWTH=1024KB)
LOG ON
(Name = 'SalesDB_log', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\SalesDB_log.ldf',SIZE=2048KB,MAXSIZE=2048GB,FILEGROWTH=10%)
COLLATE SQL_Latin1_General_CP1_CI_AS
--6
USE CUST_DB
ALTER DATABASE CUST_DB
ADD FILEGROUP FG_ReadOnly
--7
USE CUST_DB
ALTER DATABASE CUST_DB
ADD FILE (Name = 'SalesDB', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\Cust_DB.ndf')
TO FILEGROUP FG_ReadOnly ALTER DATABASE CUST_DB
MODIFY FILEGROUP FG_ReadOnly DEFAULT
--9
CREATE DATABASE AdventureWorks2019, FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER001\MSSQL\DATA\AdventureWorks_data_100.ss')
AS SNAPSHOT OF AdventureWorks2019;
go